version: '3.0'

services:
  giver:
    build: giver
    restart: always
    links: 
      - rabbit
  receiver:
    build: receiver
    restart: always
    links: 
      - rabbit
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
